#!/usr/bin/env python3
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from build_production import ASSEMBLED_DIR, PROD_ROOT, iter_markdown_blocks

METHOD_B_DIR = PROD_ROOT / "method_b_typst"
TEMPLATES_DIR = METHOD_B_DIR / "templates"
GENERATED_DIR = METHOD_B_DIR / "generated"
OUTPUT_DIR = METHOD_B_DIR / "output"
BODY_TYP = GENERATED_DIR / "body.typ"

DESIGNS = [
    "design_01_classic",
    "design_02_modern_navy",
    "design_03_minimal_journal",
    "design_04_elegant_frontmatter",
    "design_05_defense_copy",
]


def ensure_dirs() -> None:
    for directory in [METHOD_B_DIR, TEMPLATES_DIR, GENERATED_DIR, OUTPUT_DIR]:
        directory.mkdir(parents=True, exist_ok=True)


def typst_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def generate_body(md_path: Path) -> Path:
    """Generate Typst data blocks from the assembled Markdown source.

    The generated file is intentionally data-only so design templates can render
    the same scientific text in different visual styles without duplicating or
    manually editing manuscript content.
    """
    blocks: list[str] = []
    for kind, data in iter_markdown_blocks(md_path.read_text(encoding="utf-8")):
        if kind == "chaptertitle":
            chapter_number, chapter_name = (data.split("|||", 1) + [""])[:2]
            blocks.append(
                f"  (kind: \"chaptertitle\", chapter: {typst_string(chapter_number)}, "
                f"title: {typst_string(chapter_name)}),"
            )
        elif kind == "frontmatter":
            blocks.append(f"  (kind: \"frontmatter\", title: {typst_string(data)}),")
        elif kind in {"h1", "h2", "paragraph"}:
            blocks.append(f"  (kind: \"{kind}\", text: {typst_string(data)}),")
        elif kind == "image":
            caption, rel_path = data.split("|||", 1)
            image_path = (md_path.parent / rel_path).resolve()
            try:
                typst_path = image_path.relative_to(GENERATED_DIR).as_posix()
            except ValueError:
                typst_path = Path("../../assembled") / image_path.name
                typst_path = typst_path.as_posix()
            blocks.append(
                f"  (kind: \"image\", caption: {typst_string(caption)}, "
                f"path: {typst_string(typst_path)}),"
            )
        elif kind == "pagebreak":
            blocks.append("  (kind: \"pagebreak\"),")

    body = (
        "// AUTO-GENERATED by production/src/build_typst.py.\n"
        "// Do not edit this file manually; edit content/*.md for scientific text\n"
        "// or production/method_b_typst/templates/*.typ for design changes.\n\n"
        "#let manuscript_blocks = (\n"
        + "\n".join(blocks)
        + "\n)\n"
    )
    BODY_TYP.write_text(body, encoding="utf-8")
    return BODY_TYP


def write_design_entry(design: str) -> Path:
    entry = GENERATED_DIR / f"{design}.typ"
    entry.write_text(
        f"// AUTO-GENERATED entry point for {design}.\n"
        f"#import \"../templates/{design}.typ\": document, render-manuscript\n"
        "#import \"body.typ\": manuscript_blocks\n\n"
        "#show: document\n"
        "#render-manuscript(manuscript_blocks)\n",
        encoding="utf-8",
    )
    return entry


def write_default_main() -> None:
    main = METHOD_B_DIR / "main.typ"
    if main.exists():
        return
    main.write_text(
        "// Default Method B Typst entry point.\n"
        "// The production build uses generated/design_*.typ to compile all designs.\n"
        "// Compile this file after running build_all.py if you only need the classic design.\n"
        "#import \"templates/design_01_classic.typ\": document, render-manuscript\n"
        "#import \"generated/body.typ\": manuscript_blocks\n\n"
        "#show: document\n"
        "#render-manuscript(manuscript_blocks)\n",
        encoding="utf-8",
    )


def compile_design(entry: Path, out_pdf: Path) -> bool:
    typst = shutil.which("typst")
    if typst is None:
        print("WARNING: typst is not installed; Method B PDF compilation was skipped.")
        return False

    result = subprocess.run(
        [typst, "compile", str(entry), str(out_pdf)],
        cwd=METHOD_B_DIR,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        print(f"WARNING: Typst failed for {entry.name}; continuing with remaining outputs.")
        if result.stdout.strip():
            print(result.stdout.strip())
        if result.stderr.strip():
            print(result.stderr.strip())
        return False
    return True


def run_method_b(md_path: Path | None = None) -> None:
    ensure_dirs()
    write_default_main()
    if md_path is None:
        md_path = ASSEMBLED_DIR / "comprehensive_research.md"
    if not md_path.exists():
        raise FileNotFoundError(f"Assembled Markdown not found: {md_path}")

    body_path = generate_body(md_path)
    print(f"Method B generated body: {body_path}")

    compiled = 0
    for design in DESIGNS:
        entry = write_design_entry(design)
        out_pdf = OUTPUT_DIR / f"{design}.pdf"
        if compile_design(entry, out_pdf):
            compiled += 1
            print(f"Method B PDF: {out_pdf}")

    if compiled == 0:
        print("WARNING: No Method B PDFs were produced. Install typst to enable Typst PDF output.")
    else:
        print(f"Method B completed: {compiled}/{len(DESIGNS)} PDFs produced.")


def main() -> None:
    run_method_b()


if __name__ == "__main__":
    main()
